name: Deploy Next.js

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Prepare Build
        run: |
          mkdir deploy
          cp -r .next/standalone deploy/
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/
          cp -r public deploy/

      - name: Compress
        run: tar -czf deploy.tar.gz deploy

      - name: Upload Build
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "deploy.tar.gz"
          target: "/var/opt/site-admin-dashboard"

      - name: Replace Build + Restart PM2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |

            cd /var/opt/site-admin-dashboard

            tar -xzf deploy.tar.gz
            rm deploy.tar.gz

            echo "Replace standalone..."
            cp -rf deploy/standalone/* .next/standalone/

            echo "Replace static..."
            cp -rf deploy/.next/static .next/standalone/.next/

            echo "Replace public..."
            cp -rf deploy/public/* .next/standalone/public/

            rm -rf deploy

            sudo pm2 restart ecosystem.config.js
            sudo pm2 save
